### ISSUE TITLE
Entity Tracker

### ISSUE THREAD

**Issue by ghost** [epolixa/Bityard#1]
Sitting crashes the server

using: modpack of june 5th
---
I typed the first line of the entitytracker error: net.minecraft.entity.EntityTracker.func_72788_a
into Google which brought up some mc forum threads

http://www.minecraftforge.net/forum/topic/29592-server-crashing/?do=findComment&comment=155621

https://forums.spongepowered.org/t/server-cashed-need-help-description-exception-in-server-tick-loop/13587/4

http://www.minecraftforum.net/forums/support/modded-client-support/1955886-mine-crash?comment=15

http://www.minecraftforge.net/forum/topic/30981-possible-tick-issue-relating-to-either-forge-or-installed-mods/

From these threads it seems like some mod is messing with the entity tracker, a mod is trying to spawn an entity in the world from the wrong thread. So it's a threading issue, though you probably knew that already.

Not sure how to fix it though :(

I'll link this to the Trello board, just thought that it'd be difficult to read from a tiny card

**Comment by epolixa** [comment]
Sitting spawns a "Seat" entity into the world that does nothing other than provide the player something to ride. The Seat entity is immediately killed/removed when the player dismounts it. 

I haven't noticed this crash happening besides when someone tries to sit on a chisels & bits block. So I'm led to believe the game doesn't like trying to spawn an entity in a space occupied by chisels & bits stuff (weird collision checking?) but it is really hard to be sure. The error itself is very vague.

One fix idea I have is rather than spawning the Seat right at the player's feet, it spawns at their head or slightly higher and offsets the riding animation a bit. So it then likely wouldn't have issues trying to spawn inside a strange block.

**Comment by epolixa** [comment]
fixed by adding `synchronized` blocks around sensitive functionality (spawning the Seat)
